Sleep(2000)
ControlFocus("Open","","Edit1")
Sleep(2000)
ControlSetText("Open","","Edit1","C:\Users\Y-NEW\Documents\New Microsoft Word Document.docx")
Sleep(2000)
ControlFocus("Open","","Button1")
Sleep(1000)
ControlClick("Open","","Button1")
